collections_dir: docs_content

collections:
  scratch:
    output: true
  godot:
    output: true
  java:
    output: true
  c++:
    output: true
# <name>:
#   output: true

defaults:
  - scope:
      type: "scratch"
    values:
      layout: "article"
  - scope:
      type: "godot"
    values:
      layout: "article"
  - scope:
      type: "java"
    values:
      layout: "article"
  - scope:
      type: "c++"
    values:
      layout: "article"
# - scope:
#     type: "<name>"
#   values:
#     layout: "article"

url: "https://lg-ks-programmierag.github.io"
baseurl: ""